[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
html2text = "0.13.5"
reqwest = { version = "0.12.9", features = ["blocking"] }
scraper = "0.21.0"
